#!/bin/bash
source /home/onufrienko/mlops_practice/myenv/bin/activate
echo "-----Генерация данных (начало)-----"
python3 /home/onufrienko/mlops_practice/lab2/data_creation.py
echo "-----Генерация данных (конец)-----"
echo "-----Предварительная обработка данных (начало)-----"
python3 /home/onufrienko/mlops_practice/lab2/data_preprocessing.py
echo "-----Предварительная обработка данных (конец)-----"
echo "-----Подготовка модели (начало)-----"
python3 /home/onufrienko/mlops_practice/lab2/model_preparation.py
echo "-----Подготовка модели (конец)-----"
echo "-----Тестирование модели (начало)-----"
python3 /home/onufrienko/mlops_practice/lab2/model_testing.py
echo "-----Тестирование модели (конец)-----"
